spring:
  application:
    name: medical-record-service
  data:
    mongodb:
      uri: mongodb+srv://mridulbindal4_db_user:V248ypNBVyet8FlI@cluster0.4l8zwaj.mongodb.net/medicalrecorddb?appName=Cluster0

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
